import { faker } from '@faker-js/faker';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Faker runs here, once, rather than 500,000 times at runtime. The corpus then
// composes records by indexing into these pools, which is what keeps a
// 100,000-document archive cheap to hold in memory.

const SEED = 20260901;
const NAME_COUNT = 2000;
const OUTPUT = resolve('src/server/corpus/pools.generated.ts');

const GIVEN_NAMES = [
  'Rahim',
  'Karim',
  'Fatima',
  'Ayesha',
  'Nusrat',
  'Tanvir',
  'Shahin',
  'Mizanur',
  'Sultana',
  'Rubel',
  'Jahangir',
  'Sabina',
  'Nasrin',
  'Anwar',
  'Habib',
  'Rokeya',
  'Shamim',
  'Farhana',
  'Imran',
  'Salma',
  'Kamrul',
  'Rina',
  'Delwar',
  'Monira',
  'Arif',
  'Shirin',
  'Jamal',
  'Taslima',
  'Bashir',
  'Nazma',
  'Rafiq',
  'Hasina',
  'Sohel',
  'Rehana',
  'Masud',
  'Parvin',
  'Alamgir',
  'Shefali',
  'Ruhul',
  'Momena',
  'Iqbal',
  'Rahima',
  'Nazrul',
  'Shilpi',
  'Faruk',
  'Jesmin',
  'Mahmud',
  'Ruma',
  'Selim',
  'Kohinoor',
  'Abdul',
  'Marium',
  'Bablu',
  'Shahnaz',
  'Milon',
  'Rashida',
];

const FAMILY_NAMES = [
  'Ahmed',
  'Islam',
  'Hossain',
  'Rahman',
  'Khan',
  'Chowdhury',
  'Begum',
  'Akter',
  'Uddin',
  'Ali',
  'Miah',
  'Sarker',
  'Das',
  'Roy',
  'Bhuiyan',
  'Talukder',
  'Sheikh',
  'Mollah',
  'Howlader',
  'Biswas',
  'Mondal',
  'Sikder',
  'Gazi',
  'Halder',
];

const DISTRICTS = [
  'Dhaka',
  'Chattogram',
  'Khulna',
  'Rajshahi',
  'Sylhet',
  'Barishal',
  'Rangpur',
  'Mymensingh',
  "Cox's Bazar",
  'Cumilla',
  'Noakhali',
  'Jashore',
  'Bogura',
  'Dinajpur',
  'Faridpur',
  'Tangail',
  'Pabna',
  'Kushtia',
  'Jamalpur',
  'Netrokona',
  'Satkhira',
  'Patuakhali',
  'Bhola',
  'Feni',
  'Brahmanbaria',
  'Habiganj',
  'Moulvibazar',
  'Sunamganj',
  'Gazipur',
  'Narayanganj',
  'Narsingdi',
  'Manikganj',
  'Munshiganj',
  'Kishoreganj',
  'Sherpur',
  'Rajbari',
  'Madaripur',
  'Gopalganj',
  'Shariatpur',
  'Chuadanga',
  'Meherpur',
  'Magura',
  'Jhenaidah',
  'Narail',
  'Bagerhat',
  'Pirojpur',
  'Jhalokati',
  'Barguna',
  'Sirajganj',
  'Natore',
  'Naogaon',
  'Joypurhat',
  'Chapainawabganj',
  'Nilphamari',
  'Lalmonirhat',
  'Kurigram',
  'Gaibandha',
  'Thakurgaon',
  'Panchagarh',
  'Khagrachhari',
  'Rangamati',
  'Bandarban',
  'Lakshmipur',
  'Chandpur',
];

const PROGRAMS = [
  'Maternal Health Outreach',
  'Child Nutrition',
  'Primary Education Support',
  'Flood Relief Distribution',
  'Cyclone Shelter Programme',
  'Clean Water Access',
  'Vaccination Drive',
  'Adolescent Girls Education',
  'Emergency Cash Transfer',
  'Disability Support',
  'Livelihood Training',
  'Winter Clothing Distribution',
];

// Builds a stable pool of unique full names from the curated parts.
function buildNames(): string[] {
  const seen = new Set<string>();

  while (seen.size < NAME_COUNT) {
    const given = faker.helpers.arrayElement(GIVEN_NAMES);
    const family = faker.helpers.arrayElement(FAMILY_NAMES);
    seen.add(`${given} ${family}`);
  }

  return [...seen];
}

// Builds the upazila-level locations operators actually see on a form.
function buildLocations(): string[] {
  return DISTRICTS.flatMap((district) => [
    district,
    `${district} Sadar`,
    `${faker.helpers.arrayElement(['North', 'South', 'East', 'West'])} ${district}`,
  ]);
}

function serialize(name: string, values: readonly string[]): string {
  const body = values.map((value) => `  ${JSON.stringify(value)},`).join('\n');
  return `export const ${name}: readonly string[] = [\n${body}\n];\n`;
}

faker.seed(SEED);

const contents = [
  '// Generated by scripts/generate-pools.ts. Do not edit by hand.',
  `// Seed: ${SEED}`,
  '',
  serialize('NAME_POOL', buildNames()),
  serialize('LOCATION_POOL', buildLocations()),
  serialize('PROGRAM_POOL', PROGRAMS),
].join('\n');

writeFileSync(OUTPUT, contents);

console.log(`Wrote ${OUTPUT}`);
