import { faker } from '@faker-js/faker';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

// Faker runs here, once, rather than 500,000 times at runtime. The corpus then
// composes records by indexing into these pools, which is what keeps a
// 100,000-document archive cheap to hold in memory.

const SEED = 20260901;
const NAME_COUNT = 2000;
const OUTPUT = resolve('src/server/corpus/pools.generated.ts');

const GIVEN_NAMES = [
  'Rahim',
  'Karim',
  'Fatima',
  'Ayesha',
  'Nusrat',
  'Tanvir',
  'Shahin',
  'Mizanur',
  'Sultana',
  'Rubel',
  'Jahangir',
  'Sabina',
  'Nasrin',
  'Anwar',
  'Habib',
  'Rokeya',
  'Shamim',
  'Farhana',
  'Imran',
  'Salma',
  'Kamrul',
  'Rina',
  'Delwar',
  'Monira',
  'Arif',
  'Shirin',
  'Jamal',
  'Taslima',
  'Bashir',
  'Nazma',
  'Rafiq',
  'Hasina',
  'Sohel',
  'Rehana',
  'Masud',
  'Parvin',
  'Alamgir',
  'Shefali',
  'Ruhul',
  'Momena',
  'Iqbal',
  'Rahima',
  'Nazrul',
  'Shilpi',
  'Faruk',
  'Jesmin',
  'Mahmud',
  'Ruma',
  'Selim',
  'Kohinoor',
  'Abdul',
  'Marium',
  'Bablu',
  'Shahnaz',
  'Milon',
  'Rashida',
];

const FAMILY_NAMES = [
  'Ahmed',
  'Islam',
  'Hossain',
  'Rahman',
  'Khan',
  'Chowdhury',
  'Begum',
  'Akter',
  'Uddin',
  'Ali',
  'Miah',
  'Sarker',
  'Das',
  'Roy',
  'Bhuiyan',
  'Talukder',
  'Sheikh',
  'Mollah',
  'Howlader',
  'Biswas',
  'Mondal',
  'Sikder',
  'Gazi',
  'Halder',
  'Molla',
  'Fakir',
  'Munshi',
  'Pramanik',
  'Sardar',
  'Dewan',
  'Majumder',
  'Bepari',
  'Matubbar',
  'Khatun',
  'Parvez',
  'Zaman',
  'Kabir',
  'Alam',
  'Haque',
  'Mazumdar',
];

const DISTRICTS = [
  'Dhaka',
  'Chattogram',
  'Khulna',
  'Rajshahi',
  'Sylhet',
  'Barishal',
  'Rangpur',
  'Mymensingh',
  "Cox's Bazar",
  'Cumilla',
  'Noakhali',
  'Jashore',
  'Bogura',
  'Dinajpur',
  'Faridpur',
  'Tangail',
  'Pabna',
  'Kushtia',
  'Jamalpur',
  'Netrokona',
  'Satkhira',
  'Patuakhali',
  'Bhola',
  'Feni',
  'Brahmanbaria',
  'Habiganj',
  'Moulvibazar',
  'Sunamganj',
  'Gazipur',
  'Narayanganj',
  'Narsingdi',
  'Manikganj',
  'Munshiganj',
  'Kishoreganj',
  'Sherpur',
  'Rajbari',
  'Madaripur',
  'Gopalganj',
  'Shariatpur',
  'Chuadanga',
  'Meherpur',
  'Magura',
  'Jhenaidah',
  'Narail',
  'Bagerhat',
  'Pirojpur',
  'Jhalokati',
  'Barguna',
  'Sirajganj',
  'Natore',
  'Naogaon',
  'Joypurhat',
  'Chapainawabganj',
  'Nilphamari',
  'Lalmonirhat',
  'Kurigram',
  'Gaibandha',
  'Thakurgaon',
  'Panchagarh',
  'Khagrachhari',
  'Rangamati',
  'Bandarban',
  'Lakshmipur',
  'Chandpur',
];

const PROGRAMS = [
  'Maternal Health Outreach',
  'Child Nutrition',
  'Primary Education Support',
  'Flood Relief Distribution',
  'Cyclone Shelter Programme',
  'Clean Water Access',
  'Vaccination Drive',
  'Adolescent Girls Education',
  'Emergency Cash Transfer',
  'Disability Support',
  'Livelihood Training',
  'Winter Clothing Distribution',
];

// Builds a stable pool of unique full names by shuffling the whole cross
// product. Drawing at random until the set fills cannot terminate once the
// target approaches the number of possible combinations.
function buildNames(): string[] {
  const combinations = GIVEN_NAMES.flatMap((given) =>
    FAMILY_NAMES.map((family) => `${given} ${family}`),
  );

  if (NAME_COUNT > combinations.length) {
    throw new Error(
      `NAME_COUNT is ${NAME_COUNT} but only ${combinations.length} unique names can be built. ` +
        'Add more given or family names, or lower NAME_COUNT.',
    );
  }

  return faker.helpers.shuffle(combinations).slice(0, NAME_COUNT);
}

// Builds the upazila-level locations operators actually see on a form.
function buildLocations(): string[] {
  return DISTRICTS.flatMap((district) => [
    district,
    `${district} Sadar`,
    `${faker.helpers.arrayElement(['North', 'South', 'East', 'West'])} ${district}`,
  ]);
}

function serialize(name: string, values: readonly string[]): string {
  const body = values.map((value) => `  ${JSON.stringify(value)},`).join('\n');
  return `export const ${name}: readonly string[] = [\n${body}\n];\n`;
}

faker.seed(SEED);

const contents = [
  '// Generated by scripts/generate-pools.ts. Do not edit by hand.',
  `// Seed: ${SEED}`,
  '',
  serialize('NAME_POOL', buildNames()),
  serialize('LOCATION_POOL', buildLocations()),
  serialize('PROGRAM_POOL', PROGRAMS),
].join('\n');

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, contents);

console.log(`Wrote ${OUTPUT}`);
